spring:
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
  main:
    web-application-type: none
  devtools:
    restart:
      enabled: false
  autoconfigure:
    exclude:
