spring:
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
    history:
      enabled: false
  main:
    web-application-type: none
  devtools:
    restart:
      enabled: false
  autoconfigure:
    exclude:

logging:
  level:
    root: INFO
  pattern:
    console:
  file:
    # No log file
    name:
